In [11]:
import pandas as pd
import numpy as np

In [12]:
team_matches = pd.read_csv("../data/processed/team_matches_with_form.csv")
team_matches.head()

,date,team,opponent,goals_for,goals_against,tournament,city,country,neutral,is_home,...,last_5_goal_difference,last_5_win,last_5_draw,last_5_loss,previous_matches,form_matches_used,last_5_points_per_match,last_5_goals_for_per_match,last_5_goals_against_per_match,last_5_goal_difference_per_match
0,2012-09-25,Abkhazia,Artsakh,1.0,1.0,Friendly,Sukhumi,Georgia,False,True,...,0.0,0.0,0.0,0.0,0,0,0.000000,0.000000,0.000000,0.0
1,2012-10-21,Abkhazia,Artsakh,0.0,3.0,Friendly,Stepanakert,Azerbaijan,False,False,...,0.0,0.0,1.0,0.0,1,1,1.000000,1.000000,1.000000,0.0
2,2013-09-23,Abkhazia,South Ossetia,3.0,0.0,Friendly,Sukhumi,Georgia,False,True,...,-3.0,0.0,1.0,1.0,2,2,0.500000,0.500000,2.000000,-1.5
3,2014-06-01,Abkhazia,Occitania,1.0,1.0,CONIFA World Football Cup,Östersund,Sweden,True,True,...,0.0,1.0,1.0,1.0,3,3,1.333333,1.333333,1.333333,0.0
4,2014-06-02,Abkhazia,Sápmi,2.0,1.0,CONIFA World Football Cup,Östersund,Sweden,False,False,...,0.0,1.0,2.0,1.0,4,4,1.250000,1.250000,1.250000,0.0

In [13]:
team_matches["date"] = pd.to_datetime(team_matches["date"])
team_matches.columns

Index(['date', 'team', 'opponent', 'goals_for', 'goals_against', 'tournament',
       'city', 'country', 'neutral', 'is_home', 'result', 'points',
       'goal_difference', 'win', 'draw', 'loss', 'last_5_points',
       'last_5_goals_for', 'last_5_goals_against', 'last_5_goal_difference',
       'last_5_win', 'last_5_draw', 'last_5_loss', 'previous_matches',
       'form_matches_used', 'last_5_points_per_match',
       'last_5_goals_for_per_match', 'last_5_goals_against_per_match',
       'last_5_goal_difference_per_match'],
      dtype='str')

In [14]:
home_rows = team_matches[team_matches["is_home"] == True].copy()
away_rows = team_matches[team_matches["is_home"] == False].copy()
home_rows.shape, away_rows.shape

((49450, 29), (49450, 29))

In [15]:
form_features = [
    "last_5_points_per_match",
    "last_5_goals_for_per_match",
    "last_5_goals_against_per_match",
    "last_5_goal_difference_per_match",
    "last_5_win",
    "last_5_draw",
    "last_5_loss"
]

In [16]:
[col for col in team_matches.columns if "last_5" in col]

['last_5_points',
 'last_5_goals_for',
 'last_5_goals_against',
 'last_5_goal_difference',
 'last_5_win',
 'last_5_draw',
 'last_5_loss',
 'last_5_points_per_match',
 'last_5_goals_for_per_match',
 'last_5_goals_against_per_match',
 'last_5_goal_difference_per_match']

In [17]:
team_a = home_rows[
    [
        "date",
        "team",
        "opponent",
        "goals_for",
        "goals_against",
        "result",
        "tournament",
        "neutral",
    ] + form_features
].copy()

In [18]:
team_a = team_a.rename(columns={
    "team": "team_a",
    "opponent": "team_b",
    "goals_for": "team_a_goals",
    "goals_against": "team_b_goals",
    "result": "team_a_result"
})

In [19]:
team_a = team_a.rename(columns={
    col: f"team_a_{col}" for col in form_features
})

In [20]:
team_a.head()

,date,team_a,team_b,team_a_goals,team_b_goals,team_a_result,tournament,neutral,team_a_last_5_points_per_match,team_a_last_5_goals_for_per_match,team_a_last_5_goals_against_per_match,team_a_last_5_goal_difference_per_match,team_a_last_5_win,team_a_last_5_draw,team_a_last_5_loss
0,2012-09-25,Abkhazia,Artsakh,1.0,1.0,draw,Friendly,False,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0
2,2013-09-23,Abkhazia,South Ossetia,3.0,0.0,win,Friendly,False,0.500000,0.500000,2.000000,-1.5,0.0,1.0,1.0
3,2014-06-01,Abkhazia,Occitania,1.0,1.0,draw,CONIFA World Football Cup,True,1.333333,1.333333,1.333333,0.0,1.0,1.0,1.0
5,2014-06-04,Abkhazia,South Ossetia,0.0,0.0,draw,CONIFA World Football Cup,True,1.600000,1.400000,1.200000,0.2,2.0,2.0,1.0
7,2014-06-07,Abkhazia,Occitania,0.0,1.0,loss,CONIFA World Football Cup,True,1.800000,1.800000,1.000000,0.8,2.0,3.0,0.0

In [21]:
team_b = away_rows[
    [
        "date",
        "team",
        "opponent",
    ] + form_features
].copy()

In [22]:
team_b = team_b.rename(columns={
    "team": "team_b",
    "opponent": "team_a"
})

In [23]:
team_b = team_b.rename(columns={
    col: f"team_b_{col}" for col in form_features
})

In [24]:
team_b.head()

,date,team_b,team_a,team_b_last_5_points_per_match,team_b_last_5_goals_for_per_match,team_b_last_5_goals_against_per_match,team_b_last_5_goal_difference_per_match,team_b_last_5_win,team_b_last_5_draw,team_b_last_5_loss
1,2012-10-21,Abkhazia,Artsakh,1.00,1.00,1.00,0.0,0.0,1.0,0.0
4,2014-06-02,Abkhazia,Sápmi,1.25,1.25,1.25,0.0,1.0,2.0,1.0
6,2014-06-05,Abkhazia,Padania,1.60,1.20,1.00,0.2,2.0,2.0,1.0
17,2017-06-06,Abkhazia,Kárpátalja,2.60,1.60,0.40,1.2,4.0,1.0,0.0
18,2017-06-07,Abkhazia,Northern Cyprus,2.20,1.80,0.80,1.0,3.0,2.0,0.0

In [25]:
matchups = team_a.merge(
    team_b,
    on=["date", "team_a", "team_b"],
    how="inner"
)

In [29]:
matchups.head()

,date,team_a,team_b,team_a_goals,team_b_goals,team_a_result,tournament,neutral,team_a_last_5_points_per_match,team_a_last_5_goals_for_per_match,...,team_a_last_5_win,team_a_last_5_draw,team_a_last_5_loss,team_b_last_5_points_per_match,team_b_last_5_goals_for_per_match,team_b_last_5_goals_against_per_match,team_b_last_5_goal_difference_per_match,team_b_last_5_win,team_b_last_5_draw,team_b_last_5_loss
0,2012-09-25,Abkhazia,Artsakh,1.0,1.0,draw,Friendly,False,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0
1,2013-09-23,Abkhazia,South Ossetia,3.0,0.0,win,Friendly,False,0.500000,0.500000,...,0.0,1.0,1.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0
2,2014-06-01,Abkhazia,Occitania,1.0,1.0,draw,CONIFA World Football Cup,True,1.333333,1.333333,...,1.0,1.0,1.0,3.0,6.000000,0.4,5.600000,5.0,0.0,0.0
3,2014-06-04,Abkhazia,South Ossetia,0.0,0.0,draw,CONIFA World Football Cup,True,1.600000,1.400000,...,2.0,2.0,1.0,1.0,6.666667,2.0,4.666667,1.0,0.0,2.0
4,2014-06-07,Abkhazia,Occitania,0.0,1.0,loss,CONIFA World Football Cup,True,1.800000,1.800000,...,2.0,3.0,0.0,1.8,2.200000,0.8,1.400000,2.0,3.0,0.0

In [30]:
matchups.shape

(49454, 22)

In [31]:
for col in form_features:
    matchups[f"{col}_diff"] = (
        matchups[f"team_a_{col}"] - matchups[f"team_b_{col}"]
    )

In [32]:
[col for col in matchups.columns if "diff" in col]

['team_a_last_5_goal_difference_per_match',
 'team_b_last_5_goal_difference_per_match',
 'last_5_points_per_match_diff',
 'last_5_goals_for_per_match_diff',
 'last_5_goals_against_per_match_diff',
 'last_5_goal_difference_per_match_diff',
 'last_5_win_diff',
 'last_5_draw_diff',
 'last_5_loss_diff']

In [33]:
matchups["target"] = matchups["team_a_result"]
matchups["target"].value_counts()

target
win     24202
loss    13954
draw    11298
Name: count, dtype: int64

In [34]:
metadata_columns = [
    "date",
    "team_a",
    "team_b",
    "team_a_goals",
    "team_b_goals",
    "tournament",
    "neutral",
    "target"
]

team_a_feature_columns = [f"team_a_{col}" for col in form_features]
team_b_feature_columns = [f"team_b_{col}" for col in form_features]
diff_feature_columns = [f"{col}_diff" for col in form_features]

final_columns = (
    metadata_columns
    + team_a_feature_columns
    + team_b_feature_columns
    + diff_feature_columns
)

matchup_training_data = matchups[final_columns].copy()

In [35]:
matchup_training_data.head()

,date,team_a,team_b,team_a_goals,team_b_goals,tournament,neutral,target,team_a_last_5_points_per_match,team_a_last_5_goals_for_per_match,...,team_b_last_5_win,team_b_last_5_draw,team_b_last_5_loss,last_5_points_per_match_diff,last_5_goals_for_per_match_diff,last_5_goals_against_per_match_diff,last_5_goal_difference_per_match_diff,last_5_win_diff,last_5_draw_diff,last_5_loss_diff
0,2012-09-25,Abkhazia,Artsakh,1.0,1.0,Friendly,False,draw,0.000000,0.000000,...,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0
1,2013-09-23,Abkhazia,South Ossetia,3.0,0.0,Friendly,False,win,0.500000,0.500000,...,0.0,0.0,0.0,0.500000,0.500000,2.000000,-1.500000,0.0,1.0,1.0
2,2014-06-01,Abkhazia,Occitania,1.0,1.0,CONIFA World Football Cup,True,draw,1.333333,1.333333,...,5.0,0.0,0.0,-1.666667,-4.666667,0.933333,-5.600000,-4.0,1.0,1.0
3,2014-06-04,Abkhazia,South Ossetia,0.0,0.0,CONIFA World Football Cup,True,draw,1.600000,1.400000,...,1.0,0.0,2.0,0.600000,-5.266667,-0.800000,-4.466667,1.0,2.0,-1.0
4,2014-06-07,Abkhazia,Occitania,0.0,1.0,CONIFA World Football Cup,True,loss,1.800000,1.800000,...,2.0,3.0,0.0,0.000000,-0.400000,0.200000,-0.600000,0.0,0.0,0.0

In [36]:
matchup_training_data.to_csv(
    "../data/processed/matchup_training_data.csv",
    index=False
)